#!/bin/bash
# Feed Daily Digest Generator
# Syncs commits and generates a markdown digest file
#
# Usage: generate-digest.sh [OPTIONS]
#   -o, --output FILE    Output markdown file path (default: ./feed-digest.md)
#   -l, --limit N        Number of recent commits to include (default: 100)
#   -t, --title TITLE    Digest title (default: "Feed Digest")
#   --tags TAGS          Comma-separated tags for frontmatter (default: "feed,daily-digest")
#   -h, --help           Show this help message
#
# Environment variables:
#   GITHUB_FEED_TOKEN    GitHub token (required, or retrieved from macOS Keychain)
#   FEED_DIR             Feed installation directory (default: script's parent dir)

set -e

# Defaults
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FEED_DIR="${FEED_DIR:-$(dirname "$SCRIPT_DIR")}"
OUTPUT_FILE="./feed-digest.md"
LIMIT=100
TITLE="Feed Digest"
TAGS="feed,daily-digest"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -l|--limit)
            LIMIT="$2"
            shift 2
            ;;
        -t|--title)
            TITLE="$2"
            shift 2
            ;;
        --tags)
            TAGS="$2"
            shift 2
            ;;
        -h|--help)
            head -15 "$0" | tail -13
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Get token from environment or macOS Keychain
if [ -z "$GITHUB_FEED_TOKEN" ]; then
    if command -v security &> /dev/null; then
        export GITHUB_FEED_TOKEN=$(security find-generic-password -a "$USER" -s "github-feed-token" -w 2>/dev/null || true)
    fi
fi

if [ -z "$GITHUB_FEED_TOKEN" ]; then
    echo "Error: GITHUB_FEED_TOKEN not set and not found in Keychain"
    echo "Set the environment variable or store in macOS Keychain:"
    echo "  security add-generic-password -a \"\$USER\" -s \"github-feed-token\" -w \"your-token\""
    exit 1
fi

# Verify feed binary exists
if [ ! -x "$FEED_DIR/build/feed" ]; then
    echo "Error: feed binary not found at $FEED_DIR/build/feed"
    echo "Build it with: cd $FEED_DIR && make build"
    exit 1
fi

cd "$FEED_DIR"

# Sync latest commits
echo "Syncing commits..."
./build/feed sync

# Generate digest
DATE=$(date "+%Y-%m-%d")
TAGS_YAML=$(echo "$TAGS" | sed 's/,/, /g')

cat > "$OUTPUT_FILE" << EOF
---
updated: $DATE
tags: [$TAGS_YAML]
---

# $TITLE

Last updated: $DATE

## Recent Activity

EOF

# Get commits grouped by repo
./build/feed recent --limit "$LIMIT" 2>/dev/null | \
    jq -r '.commits | group_by(.repo_name) | .[] | "### \(.[0].repo_name)\n" + (map("- **\(.author)**: \(.message | split("\n")[0])\n  - _\(.timestamp | split("T")[0])_ · \(.tags | join(", "))\n") | join(""))' >> "$OUTPUT_FILE" || true

cat >> "$OUTPUT_FILE" << EOF

---
_Generated by feed at $(date "+%H:%M")_
EOF

echo "Digest updated: $OUTPUT_FILE"
